### PR TITLE
Adding attribute "name" on "unit" node for XLIFF 2.0

### PR DESCRIPTION
**Pull request by Nyholm**
This is valid according to the specification: http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html#unit

### CODE REVIEW

**Review by bocharsky-bw — APPROVED** [review]
Agree, looks like a valid change 👍

**Review by rvanlaak — APPROVED** [review]

**Review by 20uf — APPROVED** [review]

**Comment by pimolo** [comment]
The same PR should be proposed on the Symfony repo. :+1:

**Comment by Nyholm** [comment]
It is: https://github.com/symfony/symfony/pull/26149

**Comment by Nyholm** [comment]
Thank you for the reviews

**Pull request merged**
