### PR TITLE
Prepare 1.1.0 release

### PR DESCRIPTION
**Pull request by odolbeau**

### CODE REVIEW

**Comment by odolbeau** [comment]
@php-translation/members could we move forward?

**Comment by welcoMattic** [comment]
LGTM, but I'm not very familiar with release process and side effects on other packages of php-translation. But I want to learn :wink:

**Comment by odolbeau** [comment]
I don't think there is a specific release process but I may be wrong (ping @Nyholm?).
Once released, it may broke `php-translation/symfony-bundle` which does not really support sf5.0 (yet!).

**Review by Nyholm — APPROVED** [review]

**Comment by Nyholm** [comment]
I've reviewed the diff. 

The idea of each package is that they live their own life. So the release process here is not different to any package. 

If we just follow Semver then Composer will sort out version issues. 

----------

@odolbeau Let's release this and make sure the bundle supports sf 5. =)

**Review by rvanlaak — APPROVED** [review]

**Pull request merged**
