### PR TITLE
Fix code style

### PR DESCRIPTION
**Pull request by rvanlaak**
to make CI green again before the next release.

related to https://github.styleci.io/analyses/3wOoer

### CODE REVIEW

**Comment by odolbeau** [comment]
I released 1.1.0 a bit too fast (https://github.com/php-translation/symfony-storage/releases/tag/1.1.0) :o
I you could remove Style CI, I'll replace it with github actions (php-cs-fixer + PHPStan) like in the bundle if it's OK for you?

**Review by odolbeau — APPROVED** [review]

**Comment by rvanlaak** [comment]
Great idea. Did remove the config together with this PR. I'm unable to disable StyleCI though: 
image


What about using https://github.com/jakzal/phpqa to make testing code style and phpstan reproducible locally?

**Comment by odolbeau** [comment]
> What about using https://github.com/jakzal/phpqa to make testing code style and phpstan reproducible locally?

Sure, that's exactly what we use for the bundle: https://github.com/php-translation/symfony-bundle/blob/master/.github/workflows/static.yml :)

**Comment by odolbeau** [comment]
No it's not in fact! :thinking:

**Comment by rvanlaak** [comment]
@odolbeau see https://github.com/php-translation/symfony-storage/pull/38

**Comment by Nyholm** [comment]
StyleCI is disabled. 

Im happy with merging this. 
Im also happy with leaving the exception on multiple lines.

**Comment by rvanlaak** [comment]
Then let's merge this, the work of @odolbeau on `php-cs-fixer` probably will change the code style across the whole repo.

**Review by welcoMattic — APPROVED** [review]

**Pull request merged**
