### PR TITLE
Update CI PHP and Symfony versions

### PR DESCRIPTION
**Pull request by rvanlaak**

### CODE REVIEW

**Comment by rvanlaak** [comment]
@bocharsky-bw  As you can see in the test run of this PR https://github.com/php-translation/symfony-storage/runs/5052426726?check_suite_focus=true the `common` package still seems to cause troubles

**Comment by bocharsky-bw** [comment]
Uh oh... I see now.. Actually, the master branch of common repo isn't finished yet, was started by @odolbeau and contains a lot of "unreleased" changes. I'm not sure I understand what's going on in that branch to finish all the work, so I hope @odolbeau could help finishing it and release 4.x some day. For now, I ported some good changes that were merged into master including Symfony 6 support and I'm going to release 3.2.0 there - should do the trick and unblock this PR. Thanks for head ups!

**Comment by bocharsky-bw** [comment]
@rvanlaak It's better now but still one build failed, could you handle it please?

**Review by bocharsky-bw — APPROVED** [review]
Thank you!

**Pull request merged**
