### PR TITLE
allow symfony 5

### PR DESCRIPTION
**Pull request by Jeroeny**
#SymfonyHackday

### CODE REVIEW

**Comment by Nyholm** [comment]
Are the build errors related?

**Comment by Jeroeny** [comment]
> Are the build errors related?

It looks like they aren't (correct me if I'm wrong though). As I'm seeing the same errors for master, example: https://travis-ci.org/php-translation/symfony-storage/jobs/614462341

**Review by rvanlaak — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Review by bocharsky-bw — APPROVED** [review]
Seems good to me, though would be cool to fix tests in master first and then merge here to see if all tests are still passing

**Comment by odolbeau** [comment]
@Jeroeny tests have been fixed. Could you please rebase your branch?
Thanks! :)

**Review by welcoMattic — APPROVED** [review]

**Comment by odolbeau** [comment]
Thanks @Jeroeny! :+1:

**Pull request merged**
